site_name: orphanet-parser
theme: 
  name: 'material'
  palette:
    primary: 'pink'
plugins: 
  - mkdocstrings
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
